### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by cpockrandt** [cpockrandt/PhyloCSFpp#1]
- [x] add clang support
- [x] add tests for gtf annotation to travis
- [ ] Option `--dry`: tells which species cannot be mapped. suggest which model is the best and outputs a `--species` string to speed up computation
- [x] weighted mean PhyloCSF scores instead of the mean score in annotation tools
- [ ] maf format: support tab-separation and missing scores (i.e. "a\n" lines)
- [ ] print output file path instead of just "Done"
- [ ] Check other libraries other than cblas, such as OpenBLAS

@martin-steinegger Can you look into this:

- [ ] FAQ in wiki for annotate-with-mmseqs
- [ ] add mmseqs params in phylocsf++ and forward them to mmseqs
